### ISSUE TITLE
Add game properties to be changed before launch 

### ISSUE THREAD

**Issue by jtkrauss** [jdiemke/tetris#29]
- entry level
- drop-down indicator checkbox

**Comment by jdiemke** [comment]
Hello teins,

what do you mean by "drop-down indicator checkbox"?

**Comment by teins** [comment]
An checkbox which can be checked before launching a new game and activates an drop-down preview of the stones. I mean basically the feature what you already implemented to be disabled temporarily for a higher skill sealing.
